from dagster import Definitions
from dagster_dbt import DbtProject, DbtCliResource, dbt_assets
from pathlib import Path

# Pointing Dagster to project directory and manifest.json file generated by dbt
dbt_project = DbtProject(
    project_dir=Path(__file__).parent / "olist_pipeline",
)

@dbt_assets(manifest=dbt_project.manifest_path)
def olist_dbt_assets(context, dbt: DbtCliResource):
    yield from dbt.cli(["build"], context=context).stream()

defs = Definitions(
    assets=[olist_dbt_assets],
    resources={
        "dbt": DbtCliResource(
            project_dir=dbt_project,
            profiles_dir=str(Path.home() / ".dbt"),
        ),
    },
)